spring.application.name=resume-analyzer
gemini.api.key=${GEMINI_API_KEY}

spring.datasource.url=jdbc:mysql://localhost:3306/resume_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://dpg-d6ep9djh46gs73e7qmrg-a:5432/resumeanalyzerdb
#spring.datasource.username=resumeanalyzerdb_user
#spring.datasource.password=4WSHWWeNW1blxkPcE1XqSuixzTsJOEyI
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect